export const API_ENDPOINTS = {
  SIGN_UP: "/auth/signup",
  LOG_IN: "/auth/login",
  LOG_OUT: "/auth/logout",
  GET_LOGGED_IN_USER_INFO: "/auth/zuku",
  FILE_UPLOAD: "/post/upload",
  CREATE_POST: "/post/create",
  GET_POSTS: "/post/all-posts",
  GET_MY_POSTS: "/post/my-posts",
  DELETE_POST: (postId) => `/post/delete/${postId}`,
  GET_BY_POSTID: (postId) => `/post/view/${postId}`,
  UPDATE_POST: (postId) => `/post/update/${postId}`,
  LIKE_POST: (postId) => `/post/like/${postId}`,
  UNLIKE_POST: (postId) => `/post/unlike/${postId}`,
  VIEW_POST: (postId) => `/post/view/${postId}`,
  ADD_COMMENT: (postId) => `/comment/create/${postId}`,
  GET_COMMENTS_BY_POSTID: (postId) => `/comment/${postId}`,
  DELETE_COMMENT: (commentId) => `/comment/${commentId}`,
  GET_USER_INFO: (userId) => `/user/profile/${userId}`,
  UPDATE_USER_INFO: `/user/profile`,
};
