export const API_ENDPOINTS = {
  SIGN_UP: "/auth/signup",
  LOG_IN: "/auth/login",
  LOG_OUT: "/auth/logout",
  GET_LOGGED_IN_USER_INFO: "/auth/loginUserInfo",
  FILE_UPLOAD: "/post/upload",
  CREATE_POST: "/post/createpost",
  GET_POSTS: "/post/getAllPosts",
  GET_MY_POSTS: "/post/myPosts",
  DELETE_POST: (postId) => `/post/deletePost/${postId}`,
  GET_BY_POSTID: (postId) => `/post/getPostById/${postId}`,
  UPDATE_POST: (postId) => `/post/editPost/${postId}`,
  LIKE_POST: (postId) => `/post/likePost/${postId}`,
  UNLIKE_POST: (postId) => `/post/dislikePost/${postId}`,
  VIEW_POST: (postId) => `/post/view/${postId}`,
  ADD_COMMENT: (postId) => `/comment/addComment/${postId}`,
  GET_COMMENTS_BY_POSTID: (postId) => `/comment/getComments/${postId}`,
  DELETE_COMMENT: (commentId) => `/comment/deleteComment/${commentId}`,
  GET_USER_INFO: (userId) => `/user/profile/${userId}`,
  UPDATE_USER_INFO: `/user/profile`,
};
